# Generated by Django 4.2.2 on 2023-08-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('emailSubject', models.CharField(max_length=50)),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
