# Generated by Django 4.2.2 on 2023-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_portfolio_alter_email_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Title'),
        ),
    ]
