# Generated by Django 4.2.2 on 2023-09-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_portfolio_link_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
